### ISSUE TITLE
Razor comment literals come as one large token

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/razor-compiler#173]
Other literals seem to split their Content into multiple tokens, but Razor Comments return it as one big block, which makes it hard for the Razor LSP to return good Semantic Tokens.
Scenario: 
```
`@*
 this is a comment
*@` 
```

Expected:
<RazorCommentLiteral<NodeList<"\r\n", " this is a comment", "\r\n">>>

Actual:
<RazorCommentLiteral<"\r\n this is a comment \r\n">

https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Microsoft.AspNetCore.Razor.Language/test/Legacy/CSharpRazorCommentsTest.cs#L37-L46 here's an existing test for which the expectations would change if we did this.

**Comment by 333fred** [comment]
> Note: That because lines aren't tokenized we have to split all of the content (one big string) into multiple smaller strings every time a user types lol. Basically it'll be a pretty massive perf hit in VS standards.

This doesn't make any sense to me. This is not what Roslyn does for C#, and we don't need to break up the strings into multiple smaller strings every time.

> Now make a couple edits on that page and see that the big "GetContent" allocation happens for every edit.

It doesn't follow for me how this would be the impact. If anything, with the current `GetContent` implementation, I'd expect to see _worse_ performance from that API with multiple tokens, not better.

@davidwengier, do you have any current context on this bug? I don't think it's going to be in our plans to address, and absent other information I will be closing it.

**Comment by davidwengier** [comment]
I looked at the code, and TIL that the "LSP spec forbids multi-line tokens" so I can understand why which would be helpful for us, but unless we can guarantee that the tree will never have a node that spans multiple lines, we'd need to leave this code in place anyway, so its probably debatable.
https://github.com/dotnet/razor-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/Semantic/Services/TagHelperSemanticRangeVisitor.cs#L446

I have no context on perf issues, but if this is a source of some in future, we could presumably rewrite that bit of code to loop over the source text directly and avoid the GetContent call entirely if its an issue.

**Comment by 333fred** [comment]
Alright. Given that, I'm going to close this.

**Comment by davidwengier** [comment]
Sounds fair. I logged https://github.com/dotnet/razor-tooling/issues/6756 so we don't lose the context on the perf issue.
