### ISSUE TITLE
[Helix] enable Razor tooling tests

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/razor-compiler#2]
Many of the Razor tooling tests migrated to aspnetcore in https://github.com/dotnet/aspnetcore/pull/21581 do not run on Helix since many tests contain logic that rely on relative directories. This issue tracks fixing these issues and enabling the following tests on Helix:

@NTaylorMullen doing:
- [x] Microsoft.AspNetCore.Mvc.Razor.Extensions.Version1_X.Test.csproj
- [x] Microsoft.AspNetCore.Mvc.Razor.Extensions.Version2_X.Test.csproj 
- [x] Microsoft.AspNetCore.Mvc.Razor.Extensions.Test.csproj 
- [ ] Microsoft.AspNetCore.Razor.Language.Test.csproj
- [ ] Microsoft.AspNetCore.Razor.Tools.Test.csproj
- [ ] Microsoft.CodeAnalysis.Razor.Test.csproj

@pranavkm doing:
- [x] Microsoft.NET.Sdk.Razor.Test.csproj

**Comment by pranavkm** [comment]
We considered this. In this repo, the build runs quickly enough that we think it's not incredibly urgent to update these tests to Helix. We can revisit this if test run times dramatically increase in the future.
