### ISSUE TITLE
.NET 6 - Runtime error Razor Class Library

### ISSUE THREAD

**Issue by AngeloDotNet** [dotnet/razor-compiler#227]
**Describe the bug**

I created a razor class library for creating custom html components (button, textbox, select, grid), but in the specific case of the button Visual Studio shows the error: 

`RZ10012 - Found markup element with unexpected name 'Button'. If this is intended to be a component, add a @using directive for its namespace.`

Below is the code of the BUTTON razor component

```
<label> @Label </label>
<Button type = "@ Type" disabled = "@ Disable"> @ TextButton </Button>

@code {
     [Parameter] public string Label {get; set; }
     [Parameter] public string Type {get; set; }
     [Parameter] public string TextButton {get; set; }
     [Parameter] public bool Disable {get; set; }
}
```

I tried to look for documentation on how to solve, but I have not found viable solutions to resolve this (non-blocking) report

**.NET Version:** 6

**Comment by jaredpar** [comment]
Did you mean to use `<button>` here (casing difference)?

**Comment by AngeloDotNet** [comment]
Yes the idea was to use <button> (written in lowercase)

**Comment by jaredpar** [comment]
I'm unsure what the bug report is then. If the intent was to use `<button>` then what do you believe the bug in the Razor compiler is?

**Comment by AngeloDotNet** [comment]
I'll check in the next few days, at the moment I'm not working on the component library where the button is present.
Following this verification, I will update the issue.

**Comment by AngeloDotNet** [comment]
I re-checked by reopening the project, after updating Visual Studio 2022 to version 17.2.0 and the RZ10012 warning is now no longer reported. This issue can be closed for me, as although I do not make further changes, the RZ10012 warning is no longer reported. I attach below screenshots of the razor component to which this issue refers.

![Cattura](https://user-images.githubusercontent.com/49655304/168387834-ee2af2e4-d2f6-42ad-b4e0-38fae4749886.PNG)
