### ISSUE TITLE
CascadingTypeParameter does not work when constrains are specified

### ISSUE THREAD

**Issue by eyalalonn** [dotnet/razor-compiler#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`CascadingTypeParameter` **fails to propagate the type** when generic constraint is specified, meaning, I need to annotate everything with `TItem="Person"` again in the case of `SomePage.razor` the example below for it to work.

I'm getting the following error: /Users/eyal/Development/Projects/CodeCraft/<ProjectName>/src/<ProjectName>.WebApp/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Playground_razor.g.cs(312,29): error CS0449: The 'class', 'struct', 'unmanaged', 'notnull', and 'default' constraints cannot be combined or duplicated, and must be specified first in the constraints list. [/Users/eyal/Development/Projects/CodeCraft/<ProjectName>/src/<ProjectName>.WebApp/<ProjectName>.WebApp.csproj]

##  DataGrid.razor:
```razor
@typeparam TItem where TItem : class
@attribute [CascadingTypeParameter(nameof(TItem))]

<CascadingValue Name="Parent" Value="@this" IsFixed="true">
    <table>
        @if (Header is not null)
        {
            <thead>
                <GridRow TItem="TItem">
                    @Header
                </GridRow>
            </thead>
        }
        @if (DataSource is not null || Content is not null)
        {
            <tbody>
            @if (DataSource is not null)
            {
                var itemType = typeof(TItem);
                var props = itemType.GetProperties();
                
                foreach (var item in DataSource)
                {
                    <GridRow TItem="TItem">
                        @{
                            foreach (var prop in props)
                            {
                                <GridColumn TItem="TItem">
                                    @prop.GetValue(item, null)
                                </GridColumn>
                            }
                        }
                    </GridRow>
                }
            }
            @if (Content is not null)
            {
                @Content
            }
            </tbody>
        }
    </table>
</CascadingValue>

@code {
    [Parameter]
    public RenderFragment? Header { get; set; }

    [Parameter]
    public RenderFragment? Content { get; set; }

    [Parameter]
    public IReadOnlyList<TItem>? DataSource { get; set; }

    public GridRows<TItem> Rows { get; private set; } = new();

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender && Rows.Content.Columns.Count != Rows.Header.Columns.Count)
        {
            throw new InvalidOperationException($"'{nameof(DataGrid<TItem>)}' rows contains invalid amount of columns. Each row must have the exact same amount of columns as the header.");
        }
    }
}
```
There is another small issue that is unrelated to generic constraints but as you can see in the code example above I still need to do something like this:
```
<GridRow TItem="TItem">
```
and likewise here:
```
<GridColumn TItem="TItem">
```
And if it's not specified you get the following errors:

1. DataGrid.razor(9, 17): [RZ10001] The type of component 'GridRow' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TItem'.
2. The type arguments for method 'TypeInference.CreateGridRow_1<TItem>(RenderTreeBuilder, int, int, RenderFragment)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

## SomePage.razor:
```razor
<DataGrid DataSource="@People">
    <Header>
        <GridColumn Caption="Id" />
        <GridColumn Caption="First Name"/>
        <GridColumn Caption="Last Name"/>
        <GridColumn Caption="Age"/>
    </Header>
    <Content>
        <GridRow>
            <GridColumn>26</GridColumn>
            <GridColumn>Stephani</GridColumn>
            <GridColumn>Juszczak</GridColumn>
            <GridColumn>33</GridColumn>
        </GridRow>
        <GridRow>
            <GridColumn>37</GridColumn>
            <GridColumn>Jodie</GridColumn>
            <GridColumn>Bisp</GridColumn>
            <GridColumn>63</GridColumn>
        </GridRow>
    </Content>
</DataGrid>

@code {
    private IReadOnlyList<Person> People { get; } = new []
    {
        new Person(1, "Morton", "Scarlon", 38),
        new Person(2, "Shannan", "Targett", 10),
        new Person(3, "Raimundo", "Keitley", 3),
        new Person(4, "Ronica", "Wemes", 38),
        new Person(5, "Elana", "Riggey", 14),
        new Person(6, "Bari", "Iiannone", 37),
        new Person(7, "Emmaline", "Kissick", 15),
        new Person(8, "Ravid", "Riches", 62),
        new Person(9, "Elton", "Lettson", 47),
        new Person(10, "Caprice", "Poschel", 51)
    };

    private record Person(
        int Id,
        string FirstName,
        string LastName,
        int Age);
}
```

### Expected Behavior

No errors.

`CascadingTypeParameter ` should work normally when generic constraints are specified just like it does when there aren't any constraints.

### .NET Version

6.0.301

**Comment by eyalalonn** [comment]
@MariovanZeist, @javiercn both both issues got addressed? I'll try it.

**Comment by javiercn** [comment]
@eyalalonn I think we did, but if its not addressed it would be interesting for us to know.

**Comment by eyalalonn** [comment]
@javiercn I'll check it out soon if not tomorrow. ;)

**Comment by javiercn** [comment]
@eyalalonn no worries, take your time, there's no rush.

**Comment by eyalalonn** [comment]
@javiercn `CascadingTypeParameter` works as expected with constraints but the second issue still doesn't work in version 7.0.100-preview.5.22307.18. *If you want I can create a new issue about it.*

So when I do the following in my `DataGrid.razor` component:
```
<GridRow>
<GridColumn>
```
As opposed to:
```
<GridRow TItem="TItem">
<GridColumn TItem="TItem">
```
It's still complaining

> DataGrid.razor(9, 17): [RZ10001] The type of component 'GridRow' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TItem'.
  DataGrid.razor(24, 21): [RZ10001] The type of component 'GridRow' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TItem'.
  The type arguments for method 'TypeInference.CreateGridRow_1<TItem>(RenderTreeBuilder, int, int, RenderFragment)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
  The type arguments for method 'TypeInference.CreateGridRow_2<TItem>(RenderTreeBuilder, int, int, RenderFragment)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by javiercn** [comment]
@eyalalonn I'm not sure I can grasp where the issue is. It would help if you can break the sample into files and point out where the error is being raised.

**Comment by eyalalonn** [comment]
@javiercn So this is the DataGrid.razor file:
```razor
@typeparam TItem where TItem : class
@attribute [CascadingTypeParameter(nameof(TItem))]

<CascadingValue Name="Parent" Value="@this" IsFixed="true">
    <table>
        @if (Header is not null)
        {
            <thead>
                <GridRow TItem="TItem">
                    @Header
                </GridRow>
            </thead>
        }
        @if (DataSource is not null || Content is not null)
        {
            <tbody>
            @if (DataSource is not null)
            {
                var itemType = typeof(TItem);
                var props = itemType.GetProperties();
                
                foreach (var item in DataSource)
                {
                    <GridRow TItem="TItem">
                        @{
                            foreach (var prop in props)
                            {
                                <GridColumn TItem="TItem">
                                    @prop.GetValue(item, null)
                                </GridColumn>
                            }
                        }
                    </GridRow>
                }
            }
            @if (Content is not null)
            {
                @Content
            }
            </tbody>
        }
    </table>
</CascadingValue>
```
In lines 9 I have this:
```razor
<GridRow TItem="TItem">
    @Header
</GridRow>
```
In line 24 I have this:
```razor
<GridRow TItem="TItem">
    @{
        foreach (var prop in props)
        {
            <GridColumn TItem="TItem">
                @prop.GetValue(item, null)
            </GridColumn>
        }
    }
</GridRow>
```
And finally in line 28 I have this:
```razor
<GridColumn TItem="TItem">
    @prop.GetValue(item, null)
</GridColumn>
```
Now, The `CascadingTypeParameter` is declared inside `DataGrid.razor` so my expectation is that I wouldn't have to to add `TItem="TItem"` in the  instances I pointed above but removing them would result in the following error:
> DataGrid.razor(X, Y): [RZ10001] The type of component 'SomeComponent' cannot be inferred based on the values provided. Consider specifying the type arguments directly using the following attributes: 'TItem'.

Where `SomeComponent` is a `GridRow` and `GridColumn` respectively.

I hope it's clear.

**Comment by javiercn** [comment]
@eyalalonn I'm sorry, I might not be at my best today, but I'm still not sure I can see what's going on. Could you put the code in a small repro project so that we can look at the concrete details?

**Comment by eyalalonn** [comment]
@javiercn I've attached a repro, it wouldn't compile because it would complain that `TItem` cannot be inferred so you have to add  `TItem="TItem"` on nested components inside `DataGrid.razor` as I pointed above. 

[CascadingTypeParameterDemo.zip](https://github.com/dotnet/razor-compiler/files/8927153/CascadingTypeParameterDemo.zip)

**Comment by javiercn** [comment]
@eyalalonn thanks for the additional details.

I think I see now what you mean. I think there is some confusion here. `CascadingTypeParameter` works when people is consuming your DataGrid component, but it does not apply to components within your definition.

In this case, `GridRow` and `GridColumn` need to receive the type explicitly. The type is only inferred/inherited if for example you use the component within Index.razor and use GridRow or GridColumn as part of the RenderFragments. So something like

```
<DataGrid>
  <Headers>
    <GridRow>
  </Headers>
  <Content>
    <GridColumn>
  <Content>
</DataGrid>
```

that is supposed to work, but not within `DataGrid.razor`

**Comment by eyalalonn** [comment]
@javiercn I understand, thank you.
