### ISSUE TITLE
Support route syntax highlighting in Razor page directive

### ISSUE THREAD

**Issue by JamesNK** [dotnet/razor-compiler#352]
The aspnetcore team is adding route syntax highlighting in .NET 8. It's currently working for routes specified in MVC attributes, e.g. `[HttpGet("page/{id}")]`, and minimal APIs, e.g. `app.MapGet("page/{id}", () => "")`. The final place where routes are defined is Razor.

The goal is to extend highlighting to work in a route specified with the Razor page directive. In the example screenshot below the route string parsed by the `RoutePatternFactory` has syntax highlighting applied. We want the route specified with the `@page` directive to get the same highlighting:

 ![image](https://user-images.githubusercontent.com/303201/189787360-61e4f353-45d6-4bb1-ad30-8c0770e30029.png)

The existing highlighting works via Roslyn detecting the StringSyntaxAttribute ([example with HttpGetAttribute](https://github.com/dotnet/aspnetcore/blob/c4bbe4b62b816dc36f7d1d5798c3a61e2bba5a17/src/Mvc/Mvc.Core/src/HttpGetAttribute.cs#L28)) and then running classifier code from the aspnetcore repo.

I believe the Razor compiler outputs the route in the `__typeHelper` field:

![image](https://user-images.githubusercontent.com/303201/189787527-a667a6b0-5574-4d62-917b-daf92518c90c.png)

If the `StringSyntax` attribute is added to the `__typeHelper` then Roslyn may just pick it up and automatically run the classifier for the string. Some testing will be required to verify this works, and potentially some further changes might be needed in Razor or Roslyn.

Also, standard ASP.NET Core routes used with Razor pages are slightly different from Blazor routes. The `StringSyntax` used for each should be different:

* Razor page: `StringSyntax("Route")`
* Blazor: `StringSyntax("BlazorRoute")`

cc @CyrusNajmabadi

**Comment by JamesNK** [comment]
`__typeHelper` is a variable, not a field. An attribute won't work.

Instead, you could put a comment on the string to enable the classifier. For example:

![image](https://user-images.githubusercontent.com/303201/189890287-33212929-e7ab-41ef-b61b-05d71c71efb9.png)

**Comment by davidwengier** [comment]
> `__typeHelper` is a variable, not a field. An attribute won't work.

Oh yeah.. whoops! :)

**Comment by davidwengier** [comment]
Something I realised that you might want to double check in your test @JamesNK: Does the `// language=regex` work if it is immediately follow by line mappings? 

eg:

```
// language=regex
#line 1 "foo.cs"
global::System.Object __typeHelper = "...";
```

If not, there might be some tweaks needed to Roslyns trivia handling for embedded languages, or we might need an alternate approach.

**Comment by JamesNK** [comment]
It works:

![image](https://user-images.githubusercontent.com/303201/190017526-1da38e41-9800-4a61-9264-fee025c949c5.png)
